site_name: Spark
site_url: https://sparkjs.dev/
theme:
  name: material
  favicon: assets/images/favicon.png
  custom_dir: docs/overrides
  features:
    - content.code.copy
extra_css:
  - stylesheets/spark.css
extra_javascript:
  - javascript/menu-toggle.js
nav:
  - Home: index.md
  - Getting Started: docs/index.md
  - New Features in 2.0: docs/new-features-2.0.md
  - 0.1 â†’ 2.0 Migration Guide: docs/0.1-2.0-migration-guide.md
  - Spark Level-of-Detail: docs/lod-getting-started.md
  - Overview: docs/overview.md
  - System Design: docs/system-design.md
  - SparkRenderer: docs/spark-renderer.md
  - SplatMesh: docs/splat-mesh.md
  - PackedSplats: docs/packed-splats.md
  - ExtSplats: docs/ext-splats.md
  - Loading Gsplats: docs/loading-splats.md
  - Procedural Splats: docs/procedural-splats.md
  - Splat RGBA-XYZ SDF editing: docs/splat-editing.md
  - Dyno overview: docs/dyno-overview.md
  - Dyno standard library: docs/dyno-stdlib.md
  - Level-of-Detail Deep Dive: docs/new-spark-renderer.md
  - Controls: docs/controls.md
  - Performance tuning: docs/performance.md
  - Community Resources: docs/community-resources.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
